// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  connectionId: __t.connectionId().name("connection_id"),
  page: __t.string(),
  color: __t.string(),
  isRightMouse: __t.bool().name("is_right_mouse"),
  pointsJson: __t.string().name("points_json"),
  createdAtMs: __t.u64().name("created_at_ms"),
});
