// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddStrokeBatchReducer from "../add_stroke_batch_reducer";
import UpdateCursorReducer from "../update_cursor_reducer";

export type AddStrokeBatchParams = __Infer<typeof AddStrokeBatchReducer>;
export type UpdateCursorParams = __Infer<typeof UpdateCursorReducer>;

